image:
  repository: public.ecr.aws/v6r1m8q2/energy-tracker/user-service
  tag: latest
  pullPolicy: Always

port: 8080
replicas: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70

pdb:
  enabled: false
  minAvailable: 1
